LetticiaNicoli/awesome-cafezin

README.md
Adicionando TikTok baristamarcelo
=> Adicionando TikTok baristamarcelo

README.md
=> Fix OOP delivery

README.md
- Adicionado insta do diario de um coffee lover;
- Adicionado link para o curso do senac de barista
- [ x] Li os requisitos de [contribuição]()
- [ x] Já procurei na lista e não encontrei
=> adicionado insta cofferlover e curso do senac barista

README.md
=> Adiciona Roast Cafés

README.md
=> Add lucca cafes

README.md
Fazenda Ninho da Aguia, uma fazenda em Alto Caparaó, que produz um dos melhores cafés do Brasil
Adição do Café Ninho da Águia.
O Café Ninho da Águia fica em Alto Caparaó, cidade onde fica o portal para o Pico da Bandeira, o terceiro pico mais alto do País e cidade que  visito quase todos os anos já tem uns 15 anos. Hoje a região do Caparaó produz alguns dos melhores cafés do país e o Ninho da Águia é referência lá. A história deles é muito bacana. o Clayton era surfista, morava em São Paulo e em certa época da vida resolveu ir morar no Caparaó e cuidar da fazenda da família. Ele começou a participar de concursos e a vencê-los e com muita persistência mudou o cenário da produção de café na cidade. É um lugar maravilhoso para visitar, o pai dele o Sr. Aides é um baita contador de história e …
=> Add Café Ninho da Águia

README.md
Cafés de qualidade de pequenos produtores do Brasil
=> "Add veroo"

README.md
Adicionei o Fora da Lei na tabela 
É um belo lugar pra se conhecer, normalmente tem vários métodos e grãos diferentes pra experimentar:
https://g.page/foradaleicafe
=> feat: Adds Fora da Lei café

README.md
=> adiciona social café clube

README.md
=> Adicionar Crio Café

README.md
adiciona a 4beans, torrefação de Curitiba, tanto na seção de locais para compra de café quanto na de cursos.
=> adiciona 4BEANS

README.md
Adicionando Takko Café na lista de cafezins.
=> Add Takko Café

README.md
Adicionada a Kaffe - Cafeteria e Torrefação localizada em Recife-PE.
=> Add Kaffe Café

README.md
=> Add Curto Café

README.md
Adicionado links do Não sou barista
Adicionado os links do canal do Youtube e Instagram do Não Sou Barista. Traz conteúdo totalmente em português sobre cafés, equipamentos e métodos de preparo.
=> Adicionado os links do canal do Youtube e Instagram do Não Sou Barista

README.md
Adicionando a loja de cafés especiais Grão Café que consumo e recomendo para todos,  tem preços ótimos, sempre entregam no prazo, tem planos de assinaturas e sempre detalham cada mês o café escolhido com informações da fazendo onde foi produzido o grão escolhido no mês.
=> Add Grão Café

README.md
Inclusão de novo site para a compra de cafés (em grãos ou moído por método) de Campinas/SP, chamado Virginia Coffee Roasters.
=> Add Virginia Coffee Roasters

README.md
Obrigada pela dica @cw-bbcoimbra 😃
**Issue** https://github.com/LetticiaNicoli/awesome-cafezin/issues/38
=> Add Rena Café (Ouro Preto - MG)

README.md
Adicionando a cafeteria Fuscafé, que fica em Vitória/ES, que recomendo para todos, por terem excelentes opções de cafés, sobremesas e um local agradável bem estiloso. Inclusive os cafés utilizados são torrados lá mesmo e alguns estão disponíveis pra venda no local.
- [ x ] Li os requisitos de [contribuição]()
- [ x ] Já procurei na lista e não encontrei
=> Add fuscafe

README.md
Adicionando a torrefação e cafeteria Café ao Leu, que fica em Copacabana no Rio de Janeiro e recomendo para todos, por terem diversos grãos de cafés especiais, envio com torra sempre recente e um atendimento excelente.
- [ x ] Li os requisitos de [contribuição]()
- [ x ] Já procurei na lista e não encontrei
=> Add Café ao Leu
